### ISSUE TITLE
Order of questions is mixed up

### ISSUE THREAD

**Issue by Gebbi8** [FAIR-CA-indicators/fair-ca-indicators-frontend#12]
R 1.1 can be before R1

**Comment by Fancien** [comment]
There is also the issue that the order of assessments inside a group itself is not fixed.

I think this is caused by the response delays. Each assessment is queried one by one using the `/indicators/{name}` endpoint. If a later request gets its response before a previous one, and if tasks are rendered in a first-arrived first-rendered pile, this could be the cause of the issue.

If you call the endpoint `/indicators` instead (no name given), you should receive all the indicators in the same order, every time.

**Comment by Gebbi8** [comment]
So rather call indicators to get all questions and than filter by the given ids

**Comment by Fancien** [comment]
> So rather call indicators to get all questions and than filter by the given ids

The indicators dictionary is created in the same order as in the metrics.csv file. Thus, the JSON you would receive should be in the exact same order every time.
I guess you could then render the Tasks using the indicators dict order?

**Comment by Gebbi8** [comment]
> > So rather call indicators to get all questions and than filter by the given ids
> 
> The indicators dictionary is created in the same order as in the metrics.csv file. Thus, the JSON you would receive should be in the exact same order every time. I guess you could then render the Tasks using the indicators dict order?

Yes, thats what I meant.

**Comment by Gebbi8** [comment]
implemented
